# Generated by Django 4.2.4 on 2023-08-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='api_content_title_e84f5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='api_content_genre_i_339059_idx',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='api_content_release_f79a1e_idx',
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_related', to='api.genre'),
        ),
    ]
