# Generated by Django 4.2.4 on 2023-08-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_content_api_content_title_e84f5b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_related', to='api.director'),
        ),
    ]
