# Generated by Django 4.2.4 on 2023-08-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_content_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='cast',
            new_name='cast_list',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_url',
            new_name='main_content_url',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='image_url',
            new_name='thumbnail_image_url',
        ),
        migrations.AddField(
            model_name='content',
            name='has_trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_premiere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
