# Generated by Django 4.2.4 on 2023-08-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cast_content_cast_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration_minute', models.IntegerField()),
                ('main_content_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_minute', models.IntegerField()),
                ('cast_list', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('thumbnail_image_url', models.URLField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('main_content_url', models.URLField(unique=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_premiere', models.BooleanField(default=False)),
                ('has_trailer', models.BooleanField(default=False)),
                ('movie_earnings', models.FloatField(blank=True, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_contents', to='api.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_contents', to='api.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_minute', models.IntegerField()),
                ('cast_list', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('thumbnail_image_url', models.URLField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('main_content_url', models.URLField(unique=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_premiere', models.BooleanField(default=False)),
                ('has_trailer', models.BooleanField(default=False)),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_contents', to='api.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_contents', to='api.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.series'),
        ),
    ]
