# Generated by Django 4.2.7 on 2023-12-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('page_url', models.URLField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('subscription_plan_id', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('buffering_count', models.IntegerField(default=0)),
                ('average_load_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAcquisitionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('acquisition_source', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('activity_type', models.CharField(choices=[('watched', 'Watched'), ('liked', 'Liked'), ('unliked', 'Unliked'), ('shared', 'Shared')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('playback_position', models.IntegerField(blank=True, help_text='Playback position in seconds', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('watch_duration', models.IntegerField(help_text='Duration in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fully_watched', models.BooleanField(default=False)),
                ('paused_count', models.IntegerField(default=0)),
                ('rewind_count', models.IntegerField(default=0)),
                ('fast_forward_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, choices=[('movie', 'MOVIE'), ('series', 'SERIES')], max_length=100, null=True)),
            ],
        ),
    ]
