# Generated by Django 4.2.7 on 2023-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('watch_duration', models.IntegerField(help_text='Duration in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
