# Generated by Django 4.2.7 on 2023-12-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchdata',
            name='content_type',
        ),
    ]
