# Generated by Django 4.2.7 on 2023-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0002_review_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('subscription_plan_id', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
