# Generated by Django 4.2.7 on 2023-11-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0003_movierevenue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieRevenue',
            new_name='ContentRevenue',
        ),
    ]
