# Generated by Django 4.2.7 on 2023-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0004_rename_movierevenue_contentrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchdata',
            name='fully_watched',
            field=models.BooleanField(default=False),
        ),
    ]
