# Generated by Django 4.2.7 on 2023-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0005_userwatchdata_fully_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('watched', 'Watched'), ('liked', 'Liked'), ('shared', 'Shared')], max_length=100),
        ),
    ]
