# Generated by Django 4.2.7 on 2023-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0006_useractivity_device_type_useractivity_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='device_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
