# Generated by Django 4.2.7 on 2023-11-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0008_userwatchdata_end_time_userwatchdata_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchdata',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userwatchdata',
            name='start_time',
        ),
    ]
