# Generated by Django 4.2.7 on 2023-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0009_remove_userwatchdata_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchdata',
            name='fast_forward_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwatchdata',
            name='paused_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwatchdata',
            name='rewind_count',
            field=models.IntegerField(default=0),
        ),
    ]
