# Generated by Django 4.2.7 on 2023-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0011_userwatchdata_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('buffering_count', models.IntegerField(default=0)),
                ('average_load_time', models.FloatField()),
            ],
        ),
    ]
