# Generated by Django 4.2.7 on 2023-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0013_usersessiondata_review_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='platform',
            field=models.CharField(default='', max_length=100),
        ),
    ]
