# Generated by Django 4.2.7 on 2023-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0015_alter_useractivity_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcquisitionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('acquisition_source', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField()),
            ],
        ),
    ]
