# Generated by Django 4.2.7 on 2023-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0016_useracquisitiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='playback_position',
            field=models.IntegerField(default=0, help_text='Playback position in seconds'),
        ),
    ]
