# Generated by Django 4.2.7 on 2023-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0017_useractivity_playback_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='playback_position',
            field=models.IntegerField(help_text='Playback position in seconds'),
        ),
    ]
