# Generated by Django 4.2.7 on 2023-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0018_alter_useractivity_playback_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('page_url', models.URLField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
