# Generated by Django 4.2.4 on 2023-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_content_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='main_content_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
