# Generated by Django 4.2.4 on 2023-11-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_movie_is_movie_series_is_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_movie',
        ),
        migrations.RemoveField(
            model_name='series',
            name='is_movie',
        ),
    ]
