# Generated by Django 4.2.4 on 2023-11-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_remove_movie_is_movie_remove_series_is_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_movie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='series',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
    ]
