# Generated by Django 4.2.4 on 2023-09-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_rename_main_content_url_episode_episode_content_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='main_content_url',
        ),
    ]
