# Generated by Django 4.2.4 on 2023-11-27 16:50

from django.db import migrations, models
import video_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_movie_is_movie_series_is_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='thumbnail_image_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='episode_thumbnail_image/', validators=[video_app.utils.validate_file_size, video_app.utils.validate_image_file]),
        ),
    ]
