# Generated by Django 4.2.4 on 2023-11-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_remove_episode_thumbnail_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='thumbnail_image',
            new_name='thumbnail_image_url',
        ),
    ]
