# Generated by Django 4.2.4 on 2023-09-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_alter_director_table_alter_episode_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='',
        ),
    ]
