# Generated by Django 4.2.4 on 2023-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_alter_movie_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail_image_url',
        ),
        migrations.RemoveField(
            model_name='series',
            name='thumbnail_image_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/thumbnail_image/'),
        ),
        migrations.AddField(
            model_name='series',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/thumbnail_image/'),
        ),
    ]
