# Generated by Django 4.2.4 on 2023-12-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_rename_thumbnail_image_episode_thumbnail_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='conversion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='video_app.videoconversiontype'),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoconversiontype',
            name='video_type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('MOVIE_TRAILER', 'Movie Trailer'), ('SERIES', 'Series'), ('SERIES_TRAILER', 'Series Trailer'), ('EPISODE', 'Episode')], max_length=20, unique=True),
        ),
    ]
