# Generated by Django 4.2.4 on 2023-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0007_episode_conversion_type_episode_is_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_mobile_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='is_mobile_only',
            field=models.BooleanField(default=False),
        ),
    ]
