# Generated by Django 4.2.4 on 2023-09-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0007_remove_movie_thumbnail_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_image/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_image/'),
        ),
    ]
