# Generated by Django 4.2.4 on 2023-09-07 19:54

from django.db import migrations, models
import video_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_alter_movie_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_image/', validators=[video_app.utils.validate_file_size, video_app.utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_image/', validators=[video_app.utils.validate_file_size, video_app.utils.validate_image_file]),
        ),
    ]
