# Generated by Django 4.2.4 on 2023-09-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0012_remove_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
    ]
