# Generated by Django 4.2.4 on 2023-09-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0014_catagory_movie_catagory_series_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='catagory',
            new_name='category',
        ),
    ]
