# Generated by Django 4.2.4 on 2023-09-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0015_rename_catagory_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movie_table',
        ),
    ]
