# Generated by Django 4.2.4 on 2023-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0016_alter_movie_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConversionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('MOVIE', 'Movie'), ('MOVIE_TRAILER', 'Movie Trailer'), ('SERIES', 'Series'), ('SERIES_TRAILER', 'Series Trailer')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'video_conversion_type_table',
            },
        ),
    ]
