# Generated by Django 4.2.4 on 2023-09-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0017_videoconversiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='conversion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='video_app.videoconversiontype'),
        ),
        migrations.AddField(
            model_name='series',
            name='conversion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='video_app.videoconversiontype'),
        ),
    ]
