# Generated by Django 4.2.4 on 2023-09-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0018_movie_conversion_type_series_conversion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='conversion_type',
        ),
        migrations.RemoveField(
            model_name='series',
            name='conversion_type',
        ),
    ]
