# Generated by Django 4.2.4 on 2023-09-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0024_banner_is_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='%(class)s_contents', to='video_app.genre'),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(related_name='%(class)s_contents', to='video_app.genre'),
        ),
    ]
