# Generated by Django 4.2.4 on 2023-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0025_remove_movie_genre_remove_series_genre_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
