# Generated by Django 4.2.4 on 2023-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0027_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subscription_plan_id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='subscription_plan_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='subscription_plan',
            field=models.ManyToManyField(to='video_app.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='series',
            name='subscription_plan',
            field=models.ManyToManyField(to='video_app.subscriptionplan'),
        ),
    ]
