# Generated by Django 4.2.4 on 2023-10-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0028_remove_movie_subscription_plan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='subscription_plan',
            new_name='available_under_plans',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='subscription_plan',
            new_name='available_under_plans',
        ),
    ]
