# Generated by Django 4.2.4 on 2023-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0032_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='user_id',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
