# Generated by Django 4.2.5 on 2023-10-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('payment_reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grace_period_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Exhausted', 'Exhausted'), ('Expired', 'Expired')], default='Active', max_length=50)),
                ('billing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.billinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('content_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.contentreference')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.usersubscription')),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='contents',
            field=models.ManyToManyField(through='subscription_plans.UserSubscriptionContent', to='subscription_plans.contentreference'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plans.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default='Success', max_length=50)),
                ('billing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.billinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('content_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.contentreference')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='contents',
            field=models.ManyToManyField(through='subscription_plans.SubscriptionPlanContent', to='subscription_plans.contentreference'),
        ),
    ]
