# Generated by Django 4.2.5 on 2023-10-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_streams',
            field=models.IntegerField(default=1),
        ),
    ]
