# Generated by Django 4.2.5 on 2023-10-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0003_alter_subscriptionplan_max_streams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplancontent',
            name='content_reference',
        ),
        migrations.RemoveField(
            model_name='subscriptionplancontent',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='usersubscriptioncontent',
            name='content_reference',
        ),
        migrations.RemoveField(
            model_name='usersubscriptioncontent',
            name='user_subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='contents',
        ),
        migrations.DeleteModel(
            name='ContentReference',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlanContent',
        ),
        migrations.DeleteModel(
            name='UserSubscriptionContent',
        ),
    ]
