# Generated by Django 4.2.5 on 2023-10-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0004_remove_subscriptionplancontent_content_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='email',
        ),
    ]
