# Generated by Django 4.2.5 on 2023-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0008_alter_billinginfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
