# Generated by Django 4.2.5 on 2023-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0012_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='SUM', max_length=3),
        ),
    ]
