# Generated by Django 4.2.5 on 2023-11-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0013_alter_paymenttransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
