# Generated by Django 4.2.5 on 2023-11-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0016_alter_paymenttransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('Prepared', 'Prepared'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Initiated', 'Initiated')], max_length=50),
        ),
    ]
