# Generated by Django 4.2.5 on 2023-11-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0018_alter_paymenttransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
