# Generated by Django 4.2.5 on 2023-11-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0023_alter_transactionhistory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.paymenttransaction'),
        ),
    ]
