# Generated by Django 4.2.5 on 2023-11-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0024_alter_transactionhistory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
